version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_password_here

  neo4j:
    image: neo4j:5.19
    container_name: neo4j_db
    ports:
      - "7474:7474"   # Neo4j browser
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/your_password_here
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: